### ISSUE TITLE
Oculus Body tracking is laggy after app is waken up

### ISSUE THREAD

**Issue by swang81** [oculus-samples/Unreal-Movement#2]
Dear guys,

It seems a bug for bodytracking in UE 5.3.2 and UE Oculus fork(5.3.2 ) for meta . 

1. I download the demo from oculus sample github (unity + unreal) and test them.
https://github.com/oculus-samples/Unreal-Movement
https://github.com/oculus-samples/Unity-Movement

2. build the unreal and unity sample for bodytracking and install them in the oculus quest3.  Open Apps and they all works smoothly. 

3. Sleep and wake up the headset.

**Unreal version :** I found the tracking body is very laggy but the controller play very smooth. After about 30s, it will work well. In the picture, you could found the hand cannot attach to the controller. 
**unity version:** It recover in ~2s without waiting for a long time.  

I try to print the log for the tick event. Body tracking API （GetBodyState(FOculusXRBodyState& outOculusXRBodyState, float WorldToMeters)）return the same skeleton position value within a short period of time, which results in the body cartoon not playing smoothly.   

![swang81_0-1705630689517](https://github.com/oculus-samples/Unreal-Movement/assets/7790116/c77806e7-de9c-447f-b1d6-04f86e264819)

**Comment by billorr** [comment]
Thank you for reporting the issue. We have investigated and understand the cause. A fix will be coming in the Oculus Unreal integration version v64. Please monitor https://developer.oculus.com/downloads/package/unreal-engine-5-integration/ for version v64.

**Comment by swang81** [comment]
I have tested the new UE plugin V64 in UE 5.3.2. It works without any lag. Thanks for your response. 

> Thank you for reporting the issue. We have investigated and understand the cause. A fix will be coming in the Oculus Unreal integration version v64. Please monitor https://developer.oculus.com/downloads/package/unreal-engine-5-integration/ for version v64.
